version: "3.7"
services:

  app:
    build: .
    ports:
      - 80:8080
    env_file:
      - production.env
    depends_on:
      - worker
      - redis
      - minio

  worker:
    build:
      context: ./kicad-api
      dockerfile: worker.Dockerfile
    command: celery -A src.tasks.celery worker -l INFO
    volumes:
      - ./kicad-api/src:/workspace/src
    env_file:
      - production.env
    depends_on:
      - redis
      - minio

  redis:
    image: redis:6-alpine

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    env_file:
      - production.env
    environment:
      PYTHONUNBUFFERED: 1
    command: server /data


volumes:
  minio_data:

