version: 2.1

parameters:
  run-build-code:
    type: boolean
    default: false
  run-deploy:
    type: boolean
    default: false
  run-deploy-docs:
    type: boolean
    default: false
  run-tests:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build server docker image
          command: |
            export SERVER_IMAGE=admwscki/keyboard-tools-server:circleci
            set +o pipefail
            docker load -i server-image.tar | true
            docker build -t ${SERVER_IMAGE} -f deploy/Dockerfile .
            docker save -o server-image.tar ${SERVER_IMAGE}
      - run:
          name: Build worker docker image
          command: |
            export WORKER_IMAGE=admwscki/keyboard-tools-kicad:circleci
            docker build -t ${WORKER_IMAGE} -f kicad-api/Dockerfile kicad-api
            docker save -o worker-image.tar ${WORKER_IMAGE}
      - persist_to_workspace:
          root: .
          paths:
           - server-image.tar
           - worker-image.tar
  test:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - attach_workspace:
          at: .
      - run:
          name: Load docker images
          command: |
            docker load -i server-image.tar
            docker load -i worker-image.tar
      - run:
          name: Run tools stack
          working_directory: tests
          command: |
            export TAG=circleci
            docker-compose -f docker-compose.yml -f ../kicad-api/docker-compose.yml -f docker-compose.override.yml up -d
      - restore_cache:
          key: test-deps-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          working_directory: tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: test-deps-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
          paths:
            - "tests/venv"
      - run:
          name: Run tests
          working_directory: tests
          command: |
            . venv/bin/activate
            ./wait-for-selenium.sh pytest
      - run:
          name: Stop tools stack
          working_directory: tests
          command: |
            export TAG=circleci
            docker-compose -f docker-compose.yml -f ../kicad-api/docker-compose.yml -f docker-compose.override.yml stop
      - store_artifacts:
          path: tests/report.html
      - store_artifacts:
          path: tests/selenium.log
  deploy-images:
    docker:
      - image: cimg/base:2022.12
    steps:
      - checkout
      - setup_remote_docker
      - when: # run only on master when code or deployment scripts changed, do not run when only tests changed:
          condition:
            and:
              - equal: [ master, << pipeline.git.branch >> ]
              - or: [ << pipeline.parameters.run-build-code >>, << pipeline.parameters.run-deploy >> ]
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Load docker images
                command: |
                  docker load -i server-image.tar
                  docker load -i worker-image.tar
            - run:
                name: Tag and push Docker images
                command: |
                  export TAG=0.1.${CIRCLE_SHA1}
                  echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_LOGIN --password-stdin
                  ./deploy/tag.sh
            - add_ssh_keys:
                fingerprints:
                  - "9d:d0:f6:fc:1e:69:d1:9a:25:8f:f8:9b:cb:9d:6f:18"
            - run:
                name: Deploy on remote server
                command: ./deploy/deploy.sh
  deploy-docs:
    docker:
      - image: cimg/node:15.14.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2a:13:57:7d:9e:32:58:f3:19:ac:0c:f8:a7:34:4c:e6"
      - run:
          name: Build and deploy github pages
          working_directory: docs
          command: ./deploy.sh

workflows:
  build-test-deploy:
    when:
      or:
        - << pipeline.parameters.run-build-code >>
        - << pipeline.parameters.run-tests >>
        - << pipeline.parameters.run-deploy >>
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-images:
          requires:
            - hold
  build-docs:
    when: << pipeline.parameters.run-deploy-docs >>
    jobs:
      - deploy-docs:
          filters:
            branches:
              only: master

