name: Build and deploy documentation
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build and deploy
        run: ./deploy.sh
        working-directory: ./docs
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}


